from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
import pandas as pd


class ReportGenerator:

    def __init__(self, df, insights=""):

        self.df = df
        self.insights = insights

    def create_pdf(self):

        buffer = BytesIO()

        doc = SimpleDocTemplate(buffer)

        styles = getSampleStyleSheet()

        story = []

        story.append(
            Paragraph(
                "<b><font size=20>AI Data Analyst Pro Report</font></b>",
                styles["Title"]
            )
        )

        story.append(Spacer(1,20))

        story.append(
            Paragraph(
                "<b>Dataset Summary</b>",
                styles["Heading2"]
            )
        )

        rows = len(self.df)
        cols = len(self.df.columns)
        missing = int(self.df.isnull().sum().sum())
        duplicates = int(self.df.duplicated().sum())

        summary = [
            ["Metric","Value"],
            ["Rows",str(rows)],
            ["Columns",str(cols)],
            ["Missing Values",str(missing)],
            ["Duplicate Rows",str(duplicates)]
        ]

        table = Table(summary)

        table.setStyle(

            TableStyle([

                ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#2563EB")),

                ("TEXTCOLOR",(0,0),(-1,0),colors.white),

                ("GRID",(0,0),(-1,-1),1,colors.grey),

                ("BACKGROUND",(0,1),(-1,-1),colors.whitesmoke),

                ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),

                ("BOTTOMPADDING",(0,0),(-1,0),12)

            ])

        )

        story.append(table)

        story.append(Spacer(1,25))

        story.append(
            Paragraph(
                "<b>Columns</b>",
                styles["Heading2"]
            )
        )

        column_text = ", ".join(self.df.columns)

        story.append(
            Paragraph(
                column_text,
                styles["BodyText"]
            )
        )

        story.append(Spacer(1,25))

        story.append(
            Paragraph(
                "<b>AI Insights</b>",
                styles["Heading2"]
            )
        )

        if self.insights:

            story.append(

                Paragraph(

                    self.insights.replace("\n","<br/>"),

                    styles["BodyText"]

                )

            )

        else:

            story.append(

                Paragraph(

                    "No AI insights generated.",

                    styles["BodyText"]

                )

            )

        story.append(Spacer(1,25))

        story.append(

            Paragraph(

                "<b>Preview</b>",

                styles["Heading2"]

            )

        )

        preview = self.df.head(10)

        preview_data = [preview.columns.tolist()]

        preview_data += preview.values.tolist()

        preview_table = Table(preview_data)

        preview_table.setStyle(

            TableStyle([

                ("GRID",(0,0),(-1,-1),0.5,colors.grey),

                ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#2563EB")),

                ("TEXTCOLOR",(0,0),(-1,0),colors.white),

                ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold")

            ])

        )

        story.append(preview_table)

        story.append(Spacer(1,20))

        story.append(

            Paragraph(

                "Generated by AI Data Analyst Pro",

                styles["Italic"]

            )

        )

        doc.build(story)

        pdf = buffer.getvalue()

        buffer.close()

        return pdf